### PR TITLE
Add aarch64 architecture

### PR DESCRIPTION
**Pull request by svanrossem**
Add support for `aarch64` architecture, found in Raspberry Pi 3 B models.

### CODE REVIEW

**Comment by trizz** [comment]
Thanks for your PR! I'll test it as soon as I can and push new images.

**Review by GJPhilippi — COMMENTED** [review]
Changes seem fine, I would approve, but haven't tested a (successful) build, so I don't approve the review itself (as I also don't think I should be approving it as I am not the owner of the repository).

**Comment by svanrossem** [comment]
Any news?

**Comment by trizz** [comment]
> Any news?

Yes, building it is no problem, so I'll merge your PR, thanks! I'll also try to add some other things and will try to push a fresh `develop` tag later this evening for testing. If everything runs fine for a few days, I'll create a new `latest` tag.

**Comment by trizz** [comment]
@svanrossem Building without pushing worked fine, however, trying to build and push a new image with your change results in an error. I've pushed an [aarch64 only](https://hub.docker.com/layers/trizz/dsmr-remote-datalogger/aarch-test/images/sha256-ae77d043189a009b1b7fcff4e0ff1f28b22f58c65046f5df7a64e2c9c812891b?context=repo) (build with only `docker buildx build --platform linux/aarch64 -t trizz/dsmr-remote-datalogger:aarch-test . --push`) image, and as you can see Docker treats it as an `linux/arm64` image, which was already supported.

So for now, I've reverted your change. Please let me know if the `linux/arm64` image suffice.

**Pull request merged**
